name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build test image
        run: docker build -t crypto_project_test -f tests/Dockerfile .

      - name: Run tests
        run: docker run --rm crypto_project_test
